apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice-test
  name: microservice-test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: microservice-test
status:
  loadBalancer: {}
